version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring Nginx

artifacts:
  files:
    - '**/*'
